version: "3.8"
services:
    app:
        build: .
        image: ninamotor-be-app
        container_name: ninamotor-be-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        environment:
            - DB_HOST=db
            - DB_DATABASE=db_ninamotor
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: ninamotor-be-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: db_ninamotor
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
