version: "3.8"
services:
    app:
        build: .
        image: ninamotor-be-app
        container_name: ninamotor-be-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        environment:
            - DB_HOST=db
            - DB_DATABASE=db_ninamotor
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: ninamotor-be-nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: ninamotor-be-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: db_ninamotor
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3308:3306"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ninamotor-be-phpmyadmin
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=root
        depends_on:
            - db

volumes:
    dbdata:
